// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLZSQtqodLF3xMV-NNacebOqt4VczDcGU',
    appId: '1:214626654:web:7810595ddd911dfec71fcf',
    messagingSenderId: '214626654',
    projectId: 'books-b1c99',
    authDomain: 'books-b1c99.firebaseapp.com',
    storageBucket: 'books-b1c99.appspot.com',
    measurementId: 'G-M9QYDEKSS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChM62J_EajDmBGZ1ljjgHhkvb3_kk7OR4',
    appId: '1:214626654:android:1015c511fc7aa888c71fcf',
    messagingSenderId: '214626654',
    projectId: 'books-b1c99',
    storageBucket: 'books-b1c99.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHx-Qcx6XC7GhQJutEUxWou_DfLwoddHQ',
    appId: '1:214626654:ios:1f27cdeda5bdb0f6c71fcf',
    messagingSenderId: '214626654',
    projectId: 'books-b1c99',
    storageBucket: 'books-b1c99.appspot.com',
    iosBundleId: 'com.example.discreteStructureBooks',
  );
}
